export const FETCH_ALL_PARTS_PENDING = 'FETCH_ALL_PARTS_PENDING'
export const FETCH_ALL_PARTS_SUCCESS = 'FETCH_ALL_PARTS_SUCCESS'
export const FETCH_ALL_PARTS_FAILED = 'FETCH_ALL_PARTS_FAILED'

export const FETCH_ONE_PART_PENDING = 'FETCH_ONE_PART_PENDING'
export const FETCH_ONE_PART_SUCCESS = 'FETCH_ONE_PART_SUCCESS'
export const FETCH_ONE_PART_FAILED = 'FETCH_ONE_PART_FAILED'

export const ADD_PART_PENDING = 'ADD_PART_PENDING'
export const ADD_PART_SUCCESS = 'ADD_PART_SUCCESS'
export const ADD_PART_FAILED = 'ADD_PART_FAILED'

export const REMOVE_PART_PENDING = 'REMOVE_PART_PENDING'
export const REMOVE_PART_SUCCESS = 'REMOVE_PART_SUCCESS'
export const REMOVE_PART_FAILED = 'REMOVE_PART_FAILED'

export const UPDATE_PART_PENDING = 'UPDATE_PART_PENDING'
export const UPDATE_PART_SUCCESS = 'UPDATE_PART_SUCCESS'
export const UPDATE_PART_FAILED = 'UPDATE_PART_FAILED'