export const FETCH_ALL_VEHICLES_PENDING = 'FETCH_ALL_VEHICLES_PENDING'
export const FETCH_ALL_VEHICLES_SUCCESS = 'FETCH_ALL_VEHICLES_SUCCESS'
export const FETCH_ALL_VEHICLES_FAILED = 'FETCH_ALL_VEHICLES_FAILED'

export const FETCH_ONE_VEHICLE_PENDING = 'FETCH_ONE_VEHICLE_PENDING'
export const FETCH_ONE_VEHICLE_SUCCESS = 'FETCH_ONE_VEHICLE_SUCCESS'
export const FETCH_ONE_VEHICLE_FAILED = 'FETCH_ONE_VEHICLE_FAILED'

export const ADD_VEHICLE_PENDING = 'ADD_VEHICLE_PENDING'
export const ADD_VEHICLE_SUCCESS = 'ADD_VEHICLE_SUCCESS'
export const ADD_VEHICLE_FAILED = 'ADD_VEHICLE_FAILED'

export const REMOVE_VEHICLE_PENDING = 'REMOVE_VEHICLE_PENDING'
export const REMOVE_VEHICLE_SUCCESS = 'REMOVE_VEHICLE_SUCCESS'
export const REMOVE_VEHICLE_FAILED = 'REMOVE_VEHICLE_FAILED'

export const UPDATE_VEHICLE_PENDING = 'UPDATE_VEHICLE_PENDING'
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS'
export const UPDATE_VEHICLE_FAILED = 'UPDATE_VEHICLE_FAILED'